site_name: note
theme:
    name: material
    language: ja
    features:
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.code.select
        - content.tabs.link
        - content.tooltips
        - header.autohide
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    palette:
        - scheme: slate
          primary: cyan
          accent: cyan
          toggle:
              icon: material/toggle-switch
              name: switch ligth mode
        - scheme: default
          primary: cyan
          accent: cyan
          toggle:
              icon: material/toggle-switch
              name: switch dark mode

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - attr_list

nav:
  - 'Home': index.md
  - 'Introduction': introduction.md
  - 'Usage': usage.md
  - 'Configuration':
    - 'Environment Variables': config/environment.md
    - 'User Management': config/user-management.md
    - 'Best Practices':
      - 'DKIM, DMARC & SPF': config/best-practices/dkim_dmarc_spf.md
      - 'Auto-discovery': config/best-practices/autodiscover.md
    - 'Security':
      - 'Understanding the Ports': config/security/understanding-the-ports.md
      - 'SSL/TLS': config/security/ssl.md
      - 'Fail2Ban': config/security/fail2ban.md
      - 'Mail Encryption' : config/security/mail_crypt.md
      - 'Rspamd' : config/security/rspamd.md
    - 'Debugging': config/debugging.md
    - 'Mail Delivery with POP3': config/pop3.md
    - 'About setup.sh': config/setup.sh.md
    - 'Advanced Configuration':
        - 'Optional Configuration': config/advanced/optional-config.md
        - 'Maintenance':
          - 'Update and Cleanup': config/advanced/maintenance/update-and-cleanup.md
        - 'Override the Default Configs':
          - 'Dovecot': config/advanced/override-defaults/dovecot.md
          - 'Postfix': config/advanced/override-defaults/postfix.md
          - 'Modifications via Script': config/advanced/override-defaults/user-patches.md
        - 'LDAP Authentication': config/advanced/auth-ldap.md
        - 'Email Filtering with Sieve': config/advanced/mail-sieve.md
        - 'Email Gathering with Fetchmail': config/advanced/mail-fetchmail.md
        - 'Email Gathering with Getmail': config/advanced/mail-getmail.md
        - 'Email Forwarding':
          - 'Relay Hosts': config/advanced/mail-forwarding/relay-hosts.md
          - 'AWS SES': config/advanced/mail-forwarding/aws-ses.md
        - 'Full-Text Search': config/advanced/full-text-search.md
        - 'Kubernetes': config/advanced/kubernetes.md
        - 'IPv6': config/advanced/ipv6.md
        - 'Podman': config/advanced/podman.md
        - 'Dovecot Master Accounts': config/advanced/dovecot-master-accounts.md
  - 'Examples':
    - 'Tutorials':
      - 'Basic Installation': examples/tutorials/basic-installation.md
      - 'Mailserver behind Proxy': examples/tutorials/mailserver-behind-proxy.md
      - 'Crowdsec': examples/tutorials/crowdsec.md
      - 'Building your own Docker image': examples/tutorials/docker-build.md
      - 'Blog Posts': examples/tutorials/blog-posts.md
    - 'Use Cases':
      - 'Forward-Only Mail-Server with LDAP': examples/use-cases/forward-only-mailserver-with-ldap-authentication.md
      - 'Customize IMAP Folders': examples/use-cases/imap-folders.md
      - 'iOS Mail Push Support': examples/use-cases/ios-mail-push-support.md
      - 'Lua Authentication': examples/use-cases/auth-lua.md
  - 'FAQ' : faq.md
  - 'Contributing':
    - 'General Information': contributing/general.md
    - 'Tests': contributing/tests.md
    - 'Issues and Pull Requests': contributing/issues-and-pull-requests.md
  - 'DockerHub': https://hub.docker.com/r/mailserver/docker-mailserver/
  - 'GHCR': https://github.com/docker-mailserver/docker-mailserver/pkgs/container/docker-mailserver
